### PR TITLE
fix: make the formatter happy

### PR DESCRIPTION
**Pull request by AaronFeickert**
Formatting and lint fixes so CI can pass. Gotta get that green check mark.

### CODE REVIEW

**Comment by AaronFeickert** [comment]
Looks like `clippy` is very unhappy with variables outside of format strings. Seems unhelpful.

**Comment by sdbondi** [comment]
Looks like a change in rust, https://github.com/tari-project/tari-crypto/pull/138 uses latest nightly so that is probably why there is a sudden change in clippy

**Comment by delta1** [comment]
Probably worth pinning the nightly version for fmt so you can upgrade it only when you want to

**Comment by CjS77** [comment]
It's a really good lint, actually.
But better to make it a WARNING in `lints.toml` rather than hold the compiler version back. Then someone can come clean up after us.

**Comment by delta1** [comment]
like @sdbondi said it just needs to be `allow`ed in lints.toml (it's already just a pedantic warning and cargo lint is defaulting to deny)

**Comment by sdbondi** [comment]
> But better to make it a WARNING in lints.toml rather than hold the compiler version back. Then someone can come clean up after us.

I agree, might be a problem that you require +nightly to run cargo lints, that is `cargo +stable lints clippy` won't work until stable is on rust 1.65 (`uninlined_format_args` isn't recignised by clippy < 1.65), maybe thats ok. Otherwise, we should probably fix these lints.

**Comment by CjS77** [comment]
> I agree, might be a problem that you require +nightly to run cargo lints, that is `cargo +stable lints clippy` won't work until stable is on rust 1.65 (`uninlined_format_args` isn't recignised by clippy < 1.65), maybe thats ok. Otherwise, we should probably fix these lints.

Yes, just ran into this on #143, but I think we can live with this until these features are stabilised

**Comment by CjS77** [comment]
#143 covers this plus a few other bits and bobs, incl updating the code coverage script, so going to close this.

**Pull request closed without merging**
