### PR TITLE
Update dependencies

### LINKED ISSUE #34: Blake2 dep is outdated, updating it has some issues to fix
Blake2 0.8.1 relies on crypto-mac 0.7.0 > generic-array 0.12.3 which has the following rust-sec advisory: 

https://rustsec.org/advisories/RUSTSEC-2020-0146.html 

Bumping to Blake2 0.9.1 leads to some compilation issues to be fixed. Will take a look when I can. 

Context: tari-project/tari#2714

### PR DESCRIPTION
**Pull request by delta1**
Updates dalek, digest, sha2, and blake2 deps. Requires some changes for new deps. 

Depends on tari-project/bulletproofs#7 - compile/test is working with that change.

Tested with `bulletproofs = {version = "2.1.0", package = "tari_bulletproofs", git = "https://github.com/delta1/bulletproofs", branch = "deps"}` - cargo test passes.

Breaking changes: 
- rename `result()` to `finalize()` in Blake256 to match updated `Digest` traits 
- remove deprecated wrappers for blake3, k12, and sha3 

Also resolves #34

### CODE REVIEW

**Comment by CjS77** [comment]
Cool. We need a minor version update too since there are breaking changes here.

**Comment by delta1** [comment]
Definitely. Should I add a commit for that and also to the bulletproofs update - then we publish bulletproofs first and update this PR with passing CI?

**Comment by delta1** [comment]
@CjS77 bumped minor version and bulletproofs dep (pending tari-project/bulletproofs#7 merge and publish)

**Comment by delta1** [comment]
Drafting this, pending a new release of tari-project/bulletproofs to crates.io

**Pull request closed without merging**
