### PR TITLE
feat: qual of life improvements for pubkey display

### PR DESCRIPTION
**Pull request by CjS77**
The `Formatter` used in the rust `Display` trait has several lesser-known features that can be leveraged for making displaying public keys much nicer:

Given some public key instance, `pk`, equal to
`e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76`,

1. truncated Width formating

`format!("{pk:16}")` gives you `e2f2ae...08d2d76`

2. Padding and fills Widths > 64 characters let you pad and fill:

 `format!("{pk:*<66}")` gives
`e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76**`

3. Implementing lowerHex and UpperHex traits

Displaying a public key writes the lower hex by default, but you can now specify the hex format explicitly, including using the [expected alternate forms](https://doc.rust-lang.org/std/fmt/trait.LowerHex.html):

```rust
assert_eq!(
            format!("{pk:#x}"),
            "0xe2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76"
        );
        assert_eq!(
            format!("{pk:x}"),
            "e2f2ae0a6abc4e71a884a961c500515f58e30b6aa582dd8db6a65945e08d2d76"
        );
        assert_eq!(
            format!("{pk:#X}"),
            "0xE2F2AE0A6ABC4E71A884A961C500515F58E30B6AA582DD8DB6A65945E08D2D76"
        );
        assert_eq!(
            format!("{pk:X}"),
            "E2F2AE0A6ABC4E71A884A961C500515F58E30B6AA582DD8DB6A65945E08D2D76"
        );
```

4. Combined formats

And of course, all these format specifiers can be combined:

```rust
assert_eq!(
            format!("{pk:*^#68X}"),
            "*0xE2F2AE0A6ABC4E71A884A961C500515F58E30B6AA582DD8DB6A65945E08D2D76*"
        );
```

### CODE REVIEW

**Comment by CjS77** [comment]
Should make logs a lot nicer if this is used in Tari - esp the width specifier

**Review by sdbondi — APPROVED** [review]
Hellz yeah!

**Comment by SWvheerden** [comment]
utACK

**Comment by hansieodendaal** [comment]
Nice

**Pull request merged**
